# Generated by Django 5.0.7 on 2024-07-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customeruser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
